sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.11.0/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
# build the image
- docker build -t "$DOCKER_NAMESPACE"/armv5te-debian:build .
# test image
- docker run "$DOCKER_NAMESPACE"/armv5te-debian:build uname -a
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "FROM " Dockerfile | sed 's/.*://')
    docker tag "$DOCKER_NAMESPACE"/armv5te-debian:build "$DOCKER_NAMESPACE"/armv5te-debian:$TAG
    docker tag "$DOCKER_NAMESPACE"/armv5te-debian:build "$DOCKER_NAMESPACE"/armv5te-debian:latest
    docker push "$DOCKER_NAMESPACE"/armv5te-debian:$TAG
    docker push "$DOCKER_NAMESPACE"/armv5te-debian:latest
  fi